version: '3.8'

services:
  onboarding:
    build: .
    container_name: mass-onboarding
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/onboarding/"]
      interval: 30s
      timeout: 10s
      retries: 3
